name: push
on: [push]
jobs:
  deploy_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm install yarn
      - run: yarn install mongodb-realm-cli
      - run: realm-cli login --api-key="huiapykw" --private-api-keys"8a4b0045-5cb9-4fae-8733-b28c6f676ca9"
      - run: echo APP_ID=$(realm-cli push -y --project="627c11140f6dc8296e3983a9") | $GITHUB_ENV
